version: "3.9"
services:
  jupyter:
    container_name: CSD_Analyzer_jupyter
    image: jupyter/datascience-notebook:x86_64-ubuntu-22.04
    ports:
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ${HOME}/Project/CSD-Analyzer:/home/jovyan/work
    command: start-notebook.sh